exports.rings = {
    ["Ring 1: Limbo"]: [
        "Tower of Annoyingly Simple Trials",
        "Tower of Anger",
        "Tower of Madness",
        "Not Even A Tower",
        "Tower of Killjoys",
        "Tower of Hecc",
        "Tower of Keyboard Yeeting",
        "Tower of Stress",
        "Tower of Screen Punching",
        "Tower of Rage",
        "Tower of Impossible Expectations",
        "Tower of True Skill",
        "Thanos Tower",
        "Citadel of Laptop Splitting"
    ],
    ["Ring 2: Desire"]: [
        "Maybe A Tower",
        "Tower of Overcoming Hatred",
        "Tower of Cold Hands",
        "Tower of Traps",
        "Tower of Shattered Dreams",
        "Tower of Deep Darkness",
        "Tower of Falling and Failing",
        "Tower of Table Flipping",
        "Tower of Eternal Suffering",
        "Tower of Difficulty Chart",
        "Citadel of Wacky Strategy"
    ],
    ["Ring 3: Gluttony"]: [
        "Tower of Funny Thoughts",
        "Tower of Inverted Colours",
        "Tower of Deep Sighing",
        "Tower of Ancient Trickery",
        "Tower of Fatness",
        "Tower of Winning Every Run",
        "Tower of Slight Inconvenience",
        "Tower of Wall Hugging",
        "Tower of Lotsa Damage",
        "Tower of Despair",
        "Totally A Tower",
        "Tower of Confusion",
        "Citadel of Heights and Depths"
    ],
    ["Ring 4: Greed"]: [
        "Tower of Spiralling Heights",
        "Tower of Getting Gnomed",
        "Tower of Linonophobia",
        "Tower of Elysium",
        "Tower of Terrible Mondays",
        "Tower of Leaning Ledges",
        "Tower of Dust and Decay",
        "Tower of Holy Flip",
        "Tower of Nonsensical Platforms",
        "Tower of Corrupted Nightmares",
        "Tower of Inception",
        "Citadel of Uneasiness"
    ],
    ["Ring 5: Anger"]: [
        "Tower of Nice Views",
        "Tower of Getting Kinda Dissapointed",
        "Tower of Rigid Success",
        "Tower of Downward Mobility",
        "Tower of Obvious Chaos",
        "Tower of Floral Fury",
        "Tower of Tokyo Heights",
        "Tower of Extraordinary Obstacles",
        "Tower of Fractured Obstacles",
        "Tower of Glitching and Healing",
        "Tower of Frightening Nightmares",
        "Citadel of Contrasting Regions"
    ],
    ["Ring 6: Madness"]: [
        "Tower of Friendly Jumps",
        "Tower of Environmental Pain",
        "Tower of Radiant Realms",
        "Tower of Twisted Inquisition",
        "Tower of Inner and Outer Scaling",
        "Tower of A Depressing Future",
        "Tower of Intense Solar Chaos",
        "Tower of Dispersed Rooms",
        "Tower of Niflheim",
        "Tower of Strategic Mechanics",
        "Tower of Impossible Movement",
        "Citadel of Sythe Recognition"
    ],
    ["Ring 7: Violence"]: [
        "Tower of Rushed Building",
        "Tower of Feeling Lazy",
        "Tower of Collective Collaboration",
        "Tower of Distorted Aerodynamics",
        "Tower of Orientating Oscillating Opinions",
        "Tower of Never Giving Up, Ever",
        "Tower of Never Ending Dizziness",
        "Tower of Yearning Victor",
        "Tower of Ultraviolet",
        "Tower of Extreme Hell",
        "Tower of Terrifying Beauty",
        "Tower of Elongated Runs",
        "Citadel of True Exasperation"
    ],
    ["Ring 8: Fraud"]: [
        "Tower of Somewhat Simple Scaling",
        "Tower of Needing Basic Aptitude",
        "Tower of Vibrant Adventures",
        "Tower of Aamos' Anger",
        "Tower of Insult To Ingury",
        "Tower of Insanely Innovative Ideas",
        "Tower of Uneasy Scaling",
        "Tower of Mean Tasks",
        "Tower of Verdant Entropy",
        "Tower of Suffering Outside",
        "Tower of Externalizing Insanity",
        "Tower of Generation Failure",
        "Citadel of Constant Heart Stopping"
    ],
    ["Ring 9: Treachery"]: [
        "No"
    ]
}

exports.zones = {
    "Zone 1: Sea": [
        "Tower of Another Beginning",
        "Tower of Peaceful Happiness and Tranquility",
        "Tower of Atlantic Depths",
        "Tower of Hand Sweating",
        "Tower of Peace",
        "Tower of Mirrored Hecc",
        "Tower of Contractual Obligations",
        "Tower of Yearning Success",
        "Tower of Wanting Extra Levels",
        "Tower of Absolute Vexation",
        "Tower of Ultimately Terrifying",
        "Tower of Really Nasty Ideas",
        "Tower of Extreme Dystopia",
        "Tower of Zespluz",
        "Tower of Thinning Layers",
        "Citadel of Peril"
    ],
    "Zone 2: Surface": [
        "Tower of Buttons",
        "Tower of Slanted Anticipation",
        "Tower of Ground Level Ascension",
        "Tower of Troublesome Adventures",
        "Tower of Unearthed Discoveries",
        "Tower of Dreams and Caverns",
        "Tower of Slipping and Sliding",
        "Tower of Pleasant Fantasies",
        "Tower of Triangular Terror",
        "Tower of Extraterrestrial Enchantment",
        "Tower of Arcanium Zenturing",
        "Tower of Great Displeasure",
        "Tower of Oblivion",
        "Tower of Double Trouble",
        "Citadel of Green Stuff"
    ],
    "Zone 3: Sky": [
        "Tower of Six Feet Under",
        "Tower of Overestimating Difficulty",
        "Tower of Broken Bricks",
        "Tower of Client Object Frenzy",
        "Tower of Cracked, Crushed Cubes",
        "Tower of Xanthephobia",
        "Tower of Mild Agitation",
        "Tower of Dimensional Hopping",
        "Tower of Requiring Critical Help",
        "Tower of Cogs and Steam",
        "Tower of Infuriating Obstacles",
        "Tower of Menacing Creations",
        "Tower of Quirky Contraptions",
        "Tower of Cruel and Unusual Punishment",
        "Tower of Hopeless Hell",
        "Citadel of Tricky Situations"
    ],
    "Zone 4: Exosphere": [
        "Tower of Fairly Simple Trials",
        "Tower of Aquatic Contemplation",
        "Tower of Up Is Down",
        "Tower of Fun and Simple Trials",
        "Tower of Wicked Wedges",
        "Tower of Elevator Traveling",
        "Tower of Pure Chroma",
        "Tower of Mechanically Induced Mayhem",
        "Tower of Funky Grooves",
        "Tower of Shifting Slopes",
        "Tower of Dance Dance Destruction",
        "Tower of Tornado Vehemance",
        "Tower of Inevitable Failure",
        "Tower of Astronomically Aimless Annoyances",
        "Citadel of Quadrilaterals"
    ],
}